const SubmittedForm = {
  personalInfo: {
    firstName: "Patricio",
    lastName: "Mena",
    birthGender: "male",
    dobDay: "12",
    dobMonth: "2",
    dobYear: "1989",
    email: "pato@gmail.com",
    phone: "8134583065",
    address: "1234 Blvd Sunset",
    city: "San Diego",
    country: "USA",
    occupation: "",
    heightFt: "5",
    heightIn: "10",
    weightLbs: "150",
    hadWeightLossSurgery: true,
    referralSource: "realself",
    referralOther: "",
    desiredSurgeryMonth: "February",
    desiredSurgeryYear: "2027",
  },
  generalInfo: {
    desiredProcedures: ["breast_augmentation_with_implants"],
    desiredProcedureOther: "",
    dislikesAndDesires: "Yes ",
    interestedInChestSurgery: true,
    chestSurgeryGoals: "A to C",
  },
  medicalHistory: {
    hasIllness: true,
    illness: [
      {
        condition: "Penfigo",
        yearDiagnosed: "2020",
        description: "Remission",
      },
    ],
    hasAllergies: true,
    allergies: [
      {
        allergicTo: "Penicilin",
        reaction: "Rash",
      },
    ],
    hasDiabetes: true,
    diabetes: {
      diabetesType: "type_2",
      hgba1cResult: "6.8",
    },
    hasHeartCondition: true,
    heartConditionDetails: "Heart condition description",
    heartSymptoms: true,
    heartSymptomsDetails: "Chest pain symptoms",
    hasThyroidCondition: true,
    thyroid: {
      type: "hyperthyroidism",
      yearDiagnosed: "2020",
      isControlled: true,
    },
    hasDVT: true,
    dvtDetails: "DVT in left leg",
    hasHighBloodPressure: true,
    hasHighCholesterol: true,
    hasKidneyDisorder: true,
    hasAsthma: true,
    hasOrthopedicProblems: true,
    orthopedicDetails: "Chronic lower back",
    hasRespiratoryProblems: true,
    respiratoryDetails: "Mild sleep apnea",
    mentalHealthCondition: "anxiety",
    mentalHealthOther: "",
    hasReflux: true,
    refluxDetails: "Diagnosed in 2015",
    hasLiverDisease: true,
    liverDiseaseDetails: "Mildy fatty liver",
    hasBleedingDisorder: true,
    bleedingDisorderDetails: "Von william",
    hasVericoseVeins: true,
    vericoseVeinsDetails: "Moderate",
    hasInfectiousDisease: true,
    infectiousDiseaseDetails: "tuberculosis",
    isHIVPositive: true,
    hivMedications: [
      {
        name: "Penicilina",
        dosage: "50",
        frequency: "Once daily ",
      },
    ],
    hivLastUndetectableViralLoad: "1983-01-05",
    drinksAlcohol: true,
    alcoholDetails: " Two to three glasses of wine per week",
    smokingStatus: "quit",
    smokingAmountPerDay: "half a pack",
    smokingSince: "2017",
    usesRecreationalDrug: true,
    recreationalDrugDetails: "Cocaine about once a week",
    takesMedication: true,
    medications: [
      {
        name: "Penfigo",
        dose: "2020",
        frequency: "Twice daily",
        purpose: "Type 2",
      },
    ],
    takesPsychMeds: true,
    psychMeds: [
      {
        name: "Penicilin",
        dose: "10mg",
        frequency: "Once daily",
        purpose: "Anxiety",
      },
    ],
    hasPreviousSurgeries: true,
    surgeries: [
      {
        procedures: "c section",
        year: "2019",
        reason: "Childbirth",
      },
    ],
  },
  photos: {
    front:
      "https://res.cloudinary.com/dur53upok/image/upload/v1786036183/xfetmsevpgpwwtn3rz7o.jpg",
    back: "https://res.cloudinary.com/dur53upok/image/upload/v1786036188/tyoqrhvsjacyk0hbyrmd.jpg",
    leftSide:
      "https://res.cloudinary.com/dur53upok/image/upload/v1786036191/kplx2s1zyz38df2oowy4.jpg",
    rightSide:
      "https://res.cloudinary.com/dur53upok/image/upload/v1786036194/zlcuqfzwmmj24crhsp3k.jpg",
    additionalPhotos: [],
  },
};
